export const topLevelCategories = [
  "Accessories",
  "Bags",
  "Clothing",
  "Footwear",
  "Jewellery",
  "Underwear",
  "Watch",
];

export const secondLevelCategories = {
  Accessories: [
    "Bag Straps",
    "Belts",
    "Eyewear",
    "Gloves",
    "Hats and Caps",
    "Scarves",
    "Suspenders",
    "Ties",
  ],
  Bags: [
    "Backpacks",
    "Bum Bags",
    "Luggage",
    "Men's Bags",
    "Purses and Wallets",
    "Women's Bags",
  ],
  Clothing: [
    "Baby Clothes",
    "Bathrobes",
    "Dresses",
    "Jackets and Coats",
    "Nightwear",
    "Overalls and Dungarees",
    "Pants",
    "Skirts",
    "Upper",
  ],
  Footwear: [
    "Ballerinas",
    "Chelsea and Ankle boots",
    "Crocs",
    "Desert Boots",
    "Espadrilles",
    "Flip-Flops",
    "Formal Shoes",
    "Free Time Shoes",
    "Hiking",
    "Ladies High Boots",
    "Mary Jane Shoes",
    "Mules",
    "Pumps",
    "Rubber Boots",
    "Sandals",
    "Ski Boots",
    "Slippers",
    "Sneakers",
    "Snow Boots",
    "Trainers",
  ],
  Jewellery: [
    "Bracelets",
    "Brooches, Badges and Pins",
    "Cufflinks",
    "Earrings and Earcuffs",
    "Keyrings",
    "Necklaces, Pendants and Chains",
    "Pins and Clips",
    "Rings",
  ],
  Underwear: [
    "Bodies",
    "Bras",
    "Panties and Underpants",
    "Sets",
    "Socks",
    "Tights",
  ],
};

export const thirdLevelCategories = {
  Eyewear: ["sunglasses", "glasses"],
  Gloves: [
    "lace gloves",
    "knitted gloves",
    "moto and sport gloves",
    "leather gloves",
  ],
  "Hats and Caps": [
    "turban hat",
    "beanies and winter hats",
    "straw hat",
    "baseball caps",
    "bucket hat",
    "flat caps",
    "bowler hat",
    "fascinator",
    "classic hats and floppy hats",
    "beret",
  ],
  Ties: ["bowties", "classic ties"],
  Backpacks: [
    "outdoor backpacks",
    "city backpacks",
    "camera backpacks",
    "school backpacks",
    "backpack purse",
  ],
  Luggage: ["travel bags", "suitcases", "duffle bags", "cosmetic cases"],
  "Men's Bags": [
    "crossbody bags",
    "briefcases",
    "small messenger bags",
    "satchel",
  ],
  "Women's Bags": [
    "bucket bags",
    "hobo bags",
    "baguette bags",
    "top handle bags",
    "clutches and wristlets",
    "totes and shopper bags",
    "long strap bags",
  ],
  Dresses: [
    "blouse dresses",
    "wrap dresses",
    "blazer dresses",
    "sheath dresses",
    "knitted dresses",
    "fit & flare dresses",
    "casual dresses",
    "bodycon dress",
    "slip dress",
  ],
  "Jackets and Coats": [
    "suit jackets and tuxedos",
    "biker jacket",
    "pilot jacket",
    "knitted ponchos",
    "kimono coat",
    "puffer jackets",
    "trench coats",
    "casual jackets",
    "winter coats",
    "racer jacket",
    "windstoppers & softshells",
    "raincoats and ponchos",
    "bomber jacket",
    "baseball jacket",
    "winter jackets",
    "peacoat",
    "harrington jacket",
    "parka coat",
    "sportswear shorts",
    "wool coats",
    "duffle coat",
  ],
  "Overalls and Dungarees": [
    "winter overalls",
    "casual overalls",
    "elegant overalls",
    "work overalls",
  ],
  Pants: [
    "sportswear leggings",
    "beach pants",
    "jeans",
    "leggings",
    "leather leggings",
    "hotpants",
    "casual leggings",
    "leather shorts",
    "cargo",
    "leather trousers",
    "casual shorts",
    "sweat pants",
    "casual trousers",
    "culottes",
    "suit trousers",
    "sportswear shorts",
    "formal trousers",
    "denim shorts",
    "swim shorts",
  ],
  Skirts: [
    "leather skirts",
    "beach skirts",
    "balloon skirts",
    "formal skirts",
    "wrap skirts",
    "mermaid skirts",
    "denim skirts",
    "pencil and straight skirts",
    "pleated skirts",
    "casual skirts",
    "sportswear skirts",
    "a-line skirts",
    "tutu skirts",
    "tiered skirts",
  ],
  Upper: [
    "knitted vests",
    "wrap tops",
    "tank tops",
    "blouses",
    "knitted tops",
    "crop tops",
    "hoodies",
    "t-shirts",
    "denim shirt",
    "shirts",
    "cardigans",
    "cropped blouse",
    "shell tops",
    "tops",
    "transparent tops",
    "sweaters",
    "polo-shirts",
    "sweatshirts",
    "tunics",
    "vests",
    "bardot tops",
  ],
  "Chelsea and Ankle boots": ["elegant boots", "casual boots"],
  Sandals: ["formal sandals", "casual sandals"],
  Bodies: ["bodies", "monokinis"],
  Bras: ["swim top", "sports swim top"],
  "Panties and Underpants": [
    "boxers",
    "swim bottoms",
    "sports swim bottoms",
    "briefs",
    "boxer briefs",
    "panties",
    "thongs",
  ],
  Sets: ["sports swimsuit"],
  Socks: ["knee socks", "low cut socks", "classic socks"],
  Tights: ["stockings", "tights"],
};
