-- AlterTable
ALTER TABLE "Listing" ADD COLUMN     "auctionFloorPrice" INTEGER,
ADD COLUMN     "auctionMaxPrice" INTEGER,
ADD COLUMN     "auctionTime" INTEGER,
ADD COLUMN     "dataSource" TEXT,
ADD COLUMN     "delivery" TEXT,
ADD COLUMN     "employeeName" TEXT,
ADD COLUMN     "floorPrice" INTEGER,
ADD COLUMN     "isAuctioned" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "listType" TEXT,
ADD COLUMN     "maxPrice" INTEGER,
ADD COLUMN     "price" INTEGER,
ADD COLUMN     "type" TEXT,
ALTER COLUMN "category" DROP NOT NULL,
ALTER COLUMN "subCategoryOne" DROP NOT NULL,
ALTER COLUMN "subCategoryTwo" DROP NOT NULL;
